[ICU-360] pkgtools, out of source test update,fix 'make install' on solaris X-Commit-URL: https://ssl.icu-project.org/trac/changeset/2254

diff --git a/icu4c/source/tools/Makefile.in b/icu4c/source/tools/Makefile.in
--- a/icu4c/source/tools/Makefile.in
+++ b/icu4c/source/tools/Makefile.in
@@ -54,9 +54,10 @@ ICUDATADIR=$(pkgdatadir)/$(VERSION)
 SRCDATADIR=$(top_srcdir)/../data
 OBJDATADIR=$(top_builddir)/@RELATIVEDATADIR@
 # tmpdir is INSIDE pkgdata dir
-TMPDATADIR=./pkgdata/tmp
+TMPDATADIR=./tmp
 
-PKGDATA=./pkgdata -T ./tmp -s @DATABUILDDIR@ -O @DATABUILDDIR@/icupkg.inc -d @DATABUILDDIR@ -v -m $(MODE) 
+# relative lib links from pkgdata are the same as for tmp
+PKGDATA=../pkgdata/pkgdata -T . -s @DATABUILDDIR@ -O ./icupkg.inc -d @DATABUILDDIR@ -v -m $(MODE) 
 
 ## Install program information
 mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
@@ -152,8 +153,7 @@ DATAFILESR=$(RES_FILES)
 DATAFILES=$(DATAFILESD) $(DATAFILESC) $(DATAFILESB) $(DATAFILESR)
 
 ## Files to remove for 'make clean'
-CLEANFILES = *~ $(BRK_FILES)  ./pkgdata/tmp/
-
+CLEANFILES = *~ $(BRK_FILES)
 
 install-udata: install-pkgdata
 
@@ -162,56 +162,56 @@ install-local: all-local install-udata
 dist-local:
 
 clean-local: clean-pkgdata
-	test -z "$(CLEANFILES)" || $(RMV) $(CLEANFILES)
+	test -z "$(CLEANFILES)" || $(RMV) $(CLEANFILES) $(TMPDATADIR)/*
 
 # Clean up any old variations.. 
 distclean-local: clean-local
 	$(RMV) Makefile $(SRCDATAFILES) $(DATAFILES) $(TESTDATAD) $(BASETESTDATA) icupkg.inc
 	-@if [ -f $(TMPDATADIR)/icudata_dll.mak ]; then \
-		(cd pkgdata ; ./pkgdata -T ./tmp -m dll -p icudata -O @DATABUILDDIR@/icupkg.inc ./tmp/icudata.lst -d @DATABUILDDIR@ --clean ) \
+		(cd pkgdata ; ./pkgdata -T $(TMPDATADIR) -m dll -p icudata -O @DATABUILDDIR@/icupkg.inc $(TMPDATADIR)/icudata.lst -d @DATABUILDDIR@ --clean ) \
 	fi
 	-@if [ -f $(TMPDATADIR)/icudata_common.mak ]; then \
-		(cd pkgdata; ./pkgdata -T ./tmp -m common -p icudata -O @DATABUILDDIR@/icupkg.inc ./tmp/icudata.lst -d @DATABUILDDIR@ --clean ) \
+		(cd pkgdata; ./pkgdata -T $(TMPDATADIR) -m common -p icudata -O @DATABUILDDIR@/icupkg.inc $(TMPDATADIR)/icudata.lst -d @DATABUILDDIR@ --clean ) \
 	fi
-	-@$(RMV) ./tmp/icudata.lst  @DATABUILDDIR@/icupkg.inc @DATABUILDDIR@/*.o @DATABUILDDIR@/*.c @DATABUILDDIR@/*.mak @DATABUILDDIR@/*.lst
 	-@$(RMV) $(TMPDATADIR)
 
-@DATABUILDDIR@/icudata.lst: Makefile $(srcdir)/genrb/genrbfiles.mk
+$(TMPDATADIR)/icudata.lst: Makefile $(srcdir)/Makefile.in $(srcdir)/genrb/genrbfiles.mk $(srcdir)/makeconv/ucmfiles.mk
 	@echo Generating $@ list of data files
-	@-$(RMV) @DATABUILDDIR@/icudata.lst
+	@-$(RMV) $(TMPDATADIR)/icudata.lst
 	@for file in $(DATAFILES); do \
-	  echo `pwd`/$$file >>@DATABUILDDIR@/icudata.lst; \
+	  echo `pwd`/$$file >> $(TMPDATADIR)/icudata.lst; \
 	done;
 
-@DATABUILDDIR@/testdata.lst: Makefile
+$(TMPDATADIR)/testdata.lst: Makefile
+	@$(mkinstalldirs) $(TMPDATADIR)
 	@echo @DATABUILDDIR@/test.dat > $@
 
-@DATABUILDDIR@/icupkg.inc: icupkg.inc
-	cp icupkg.inc @DATABUILDDIR@/icupkg.inc
+$(TMPDATADIR)/icupkg.inc: pkgdata/icupkg.inc
+	@$(mkinstalldirs) $(TMPDATADIR)
+	cp pkgdata/icupkg.inc $(TMPDATADIR)/icupkg.inc
 
 # build the ICU and test data
 
-build-local build-pkgdata: @DATABUILDDIR@/icudata.lst @DATABUILDDIR@/testdata.lst  @DATABUILDDIR@/icupkg.inc $(DATAFILES) @DATABUILDDIR@/test.dat
-	$(mkinstalldirs) $(TMPDATADIR)
-	(cd pkgdata; $(PKGDATA) -p icudata @DATABUILDDIR@/icudata.lst   )
-	(cd pkgdata; $(PKGDATA) -p base    @DATABUILDDIR@/testdata.lst  )
-	(cd pkgdata; $(PKGDATA) -p base_test  @DATABUILDDIR@/testdata.lst )
-
-install-pkgdata: @DATABUILDDIR@/icudata.lst @DATABUILDDIR@/icupkg.inc
-	$(mkinstalldirs) $(TMPDATADIR)  $(DESTDIR)$(pkgdatadir)/$(VERSION)
-	(cd pkgdata; $(PKGDATA) -p icudata @DATABUILDDIR@/icudata.lst -I $(DESTDIR)$(pkgdatadir)/$(VERSION) )
-
-icupkg.inc: $(srcdir)/icupkg.inc.in  $(top_builddir)/config.status
-	cd $(top_builddir) \
-	&& CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
-
-clean-pkgdata:  @DATABUILDDIR@/icudata.lst @DATABUILDDIR@/icupkg.inc
+build-local build-pkgdata: $(TMPDATADIR)/icudata.lst $(TMPDATADIR)/testdata.lst  $(TMPDATADIR)/icupkg.inc $(DATAFILES) @DATABUILDDIR@/test.dat
 	@$(mkinstalldirs) $(TMPDATADIR)
-	-@(cd pkgdata; $(PKGDATA) -p icudata @DATABUILDDIR@/icudata.lst --clean || echo '### Warning, cannot clean up icu/data if pkgdata is already gone.' )
-	-$(RMV) @DATABUILDDIR@/icudata.lst @DATABUILDDIR@/icupkg.inc
+	(cd tmp; $(PKGDATA) -p icudata ./icudata.lst   )
+	(cd tmp; $(PKGDATA) -p base    ./testdata.lst  )
+	(cd tmp; $(PKGDATA) -p base_test  ./testdata.lst )
+
+install-pkgdata: $(TMPDATADIR)/icudata.lst $(TMPDATADIR)/icupkg.inc
+	$(mkinstalldirs) $(TMPDATADIR)  $(DESTDIR)$(pkgdatadir)/$(VERSION)
+	(cd tmp; $(PKGDATA) -p icudata ./icudata.lst -I $(DESTDIR)$(pkgdatadir)/$(VERSION) )
+
+
+clean-pkgdata:  $(TMPDATADIR)/icudata.lst $(TMPDATADIR)/icupkg.inc
+	@$(mkinstalldirs) $(TMPDATADIR)
+	-@(cd tmp; $(PKGDATA) -p icudata ./icudata.lst --clean || echo '### Warning, cannot clean up icu/data if pkgdata is already gone.' )
+	-$(RMV) $(TMPDATADIR)/icudata.lst $(TMPDATADIR)/icupkg.inc 
 
 check-local:
 
 Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
 	cd $(top_builddir) \
 	&& CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
+
+
