header test (header obsolescence form changed)
X-Trac-URL: https://ssl.icu-project.org/trac/ticket/2330



git-svn-id: http://source.icu-project.org/repos/icu/icu/trunk@10590 0a8b766c-62c9-45f9-954d-7f2943c9ead0

diff --git a/source/test/hdrtst/Makefile b/source/test/hdrtst/Makefile
--- a/source/test/hdrtst/Makefile
+++ b/source/test/hdrtst/Makefile
@@ -77,7 +77,7 @@ cpptest:
 dtest:
 	@rm -f Makefile.sub
 	@echo "Deprecation #######################################################"
-	@echo 'Should be 1 in each case if file is properly deprecated.'
+	@echo 'Should be 1 in each case if file is properly obsoleted.'
 	@for stub in `cat dfiles.txt` ; do \
 	  file=unicode/$$stub \
 	  incfile=`basename $$file .h` ; \
@@ -85,10 +85,10 @@ dtest:
 	  echo '#include "'unicode/$$incfile'.h"' > ht_$$incfile.cpp ; \
 	  echo 'void junk(){}' >> ht_$$incfile.cpp ; \
 	  echo > ht_dep.junk ; \
-          $(COMPILE.cc) -c -I. ht_$$incfile.cpp 2>&1 | sed -e 's/^.*#error[^"]*"//' | fgrep -v ht_ | tee ht_dep.junk | fgrep -v "$$incfile.h header is deprecated" ; \
+          $(COMPILE.cc) -c -I. ht_$$incfile.cpp 2>&1 | sed -e 's/^.*#error[^"]*"//' | fgrep -v ht_ | tee ht_dep.junk | fgrep -v "$$incfile.h header is obsolete" ; \
 	  RES=$$? ; \
 	  echo $$RES ; \
-	  fgrep -q "$$incfile.h header is deprecated" ht_dep.junk || echo "** FAIL Header unicode/$$incfile.h is not deprecated properly" ; \
+	  fgrep -q "$$incfile.h header is obsolete" ht_dep.junk || echo "** FAIL Header unicode/$$incfile.h is not obsoleted properly" ; \
 	  rm -f unicode/$$stub ; \
 	done
 
