ICU-1765 Header Test: test C also
X-SVN-Rev: 7981

diff --git a/icu4c/source/test/hdrtst/Makefile b/icu4c/source/test/hdrtst/Makefile
--- a/icu4c/source/test/hdrtst/Makefile
+++ b/icu4c/source/test/hdrtst/Makefile
@@ -19,6 +19,9 @@
 #    .. etc.  Anything other than zero is an error.
 #              
 #
+#  If a header fails the C compile because it's a C++ header, add it to the
+#  file named 'cxxfiles.txt' in this directory.
+#
 #
 
 include ../../config/Makefile.inc
@@ -29,28 +32,50 @@ all:
 	@echo Please read this Makefile for more information.
 	@echo run \'$(MAKE) check\' to run the test 
 
-check: hdrdir genfiles
+check: hdrdir ctest cpptest doclean
+
+# break dependency
+doclean:
+	make clean
+
+#layout not tested for path dependencies
 
 hdrdir:
 	-$(RMV) ./unicode
 	mkdir ./unicode
-	( cd ./unicode ; ln -s ../../../common/unicode/*.h ../../../i18n/unicode/*.h . )
+	( cd ./unicode ; ln -s ../../../common/unicode/*.h ../../../i18n/unicode/*.h  ../../../extra/ustdio/unicode/*.h  . )
+	rm unicode/pwin32.h
 
-genfiles:
+cpptest:
 	@rm -f Makefile.sub
 	@echo Building test harness for header files in ../../common and ../../i18n
 	@echo 'the number after the hyphen (-) refers to the exit code - should be zero!'
-	@for file in ../../common/unicode/*.h ../../i18n/unicode/*.h; do \
+	@for file in unicode/*.h; do \
 	  incfile=`basename $$file .h` ; \
-	  echo -n "  unicode/$$incfile.h 	- " ; \
+	  echo -n "C++  unicode/$$incfile.h 	- " ; \
 	  echo '#include "'unicode/$$incfile'.h"' > ht_$$incfile.cpp ; \
 	  echo 'void junk(){}' >> ht_$$incfile.cpp ; \
           $(COMPILE.cc) -c -I. ht_$$incfile.cpp ; \
 	  RES=$$? ; \
 	  echo $$RES ; \
 	done
-	make clean
+
+ctest:
+	@echo "Now, C test"
+	@rm -f Makefile.sub
+	@echo Building test harness for header files in ../../common and ../../i18n
+	@echo 'the number after the hyphen (-) refers to the exit code - should be zero!'
+	@for file in `ls unicode/*.h | fgrep -v -f ./cxxfiles.txt | tee cfiles.txt`; do \
+	  incfile=`basename $$file .h` ; \
+	  echo -n "C    unicode/$$incfile.h 	- " ; \
+	  echo '#include "'unicode/$$incfile'.h"' > ht_$$incfile.c ; \
+	  echo 'void junk(){}' >> ht_$$incfile.c ; \
+          $(COMPILE.c) -c -I. ht_$$incfile.c ; \
+	  RES=$$? ; \
+	  echo $$RES ; \
+	done
 
 distclean clean:
-	-rm -f *.h *.cpp *.o
+	-rm -f *.h *.c *.cpp *.o
 	-$(RMV) ./unicode
+
