[ICU-5279] Use __attribute__((visibility("default"))) when gcc 4 is used. X-Commit-URL: https://ssl.icu-project.org/trac/changeset/21617 Former-commit-id: ebc57ed6c51cad5d2d99cbe8cf6b7b0cc7cdbb35

diff --git a/icu4c/source/configure b/icu4c/source/configure
--- a/icu4c/source/configure
+++ b/icu4c/source/configure
@@ -3649,6 +3649,67 @@ if test "$U_DEFAULT_SHOW_DRAFT" = 0; then
 fi
 
 
+echo "$as_me:$LINENO: checking for library API export" >&5
+echo $ECHO_N "checking for library API export... $ECHO_C" >&6
+SHAREDLIBEXPORT=no
+if test "$ac_cv_c_compiler_gnu" = yes; then
+    OLD_CFLAGS="${CFLAGS}"
+    OLD_CXXFLAGS="${CXXFLAGS}"
+    CFLAGS="${CFLAGS} -fvisibility=hidden"
+    CXXFLAGS="${CXXFLAGS} -fvisibility=hidden"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+__attribute__ ((visibility ("default"))) void f(void);
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  SHAREDLIBEXPORT=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+SHAREDLIBEXPORT=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+    if test "$SHAREDLIBEXPORT" = no; then
+        CFLAGS="${OLD_CFLAGS}"
+        CXXFLAGS="${OLD_CXXFLAGS}"
+    fi
+fi
+echo "$as_me:$LINENO: result: $SHAREDLIBEXPORT" >&5
+echo "${ECHO_T}$SHAREDLIBEXPORT" >&6
+
 if test -n "$ac_tool_prefix"; then
   # Extract the first word of "${ac_tool_prefix}ranlib", so it can be a program name with args.
 set dummy ${ac_tool_prefix}ranlib; ac_word=$2
@@ -6370,12 +6431,11 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-  #include <time.h>
-
+#include <time.h>
 int
 main ()
 {
-  __timezone = 1;
+__timezone = 1;
   ;
   return 0;
 }
@@ -6429,12 +6489,11 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-    #include <time.h>
-
+#include <time.h>
 int
 main ()
 {
-    _timezone = 1;
+_timezone = 1;
   ;
   return 0;
 }
@@ -6560,12 +6619,11 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-  #include <time.h>
-
+#include <time.h>
 int
 main ()
 {
-  __daylight = 1;
+__daylight = 1;
   ;
   return 0;
 }
