ICU-5803 Porting fixes for MinGW
X-SVN-Rev: 22148

diff --git a/icu4c/source/configure b/icu4c/source/configure
--- a/icu4c/source/configure
+++ b/icu4c/source/configure
@@ -3380,22 +3380,63 @@ alpha*-*-linux-gnu)
 	fi ;;
 powerpc*-*-linux*)
 	if test "$GCC" = yes; then
-	  	icu_cv_host_frag=mh-linux
+		icu_cv_host_frag=mh-linux
 	else
-	  	icu_cv_host_frag=mh-linux-va
+		icu_cv_host_frag=mh-linux-va
 	fi ;;
 *-*-linux*) icu_cv_host_frag=mh-linux ;;
-*-*-cygwin)
+*-*-cygwin|*-*-mingw32)
 	if test "$GCC" = yes; then
-	  	icu_cv_host_frag=mh-cygwin
+		cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#ifndef __MINGW32__
+#error This is not MinGW
+#endif
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  icu_cv_host_frag=mh-mingw
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+icu_cv_host_frag=mh-cygwin
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 	else
-	  	icu_cv_host_frag=mh-cygwin-msvc
-	fi ;;
-*-*-mingw32)
-	if test "$GCC" = yes; then
-	  	icu_cv_host_frag=mh-mingw
-	else
-	  	icu_cv_host_frag=mh-cygwin-msvc
+		icu_cv_host_frag=mh-cygwin-msvc
 	fi ;;
 *-*-*bsd*|*-*-dragonfly*) 	icu_cv_host_frag=mh-bsd-gcc ;;
 *-*-aix*)
