[ICU-6112] Don't export private symbols, and bind the symbols locally on Solaris. X-Commit-URL: https://ssl.icu-project.org/trac/changeset/23142 Former-commit-id: 4cc088397f7623a86a1b43a009cce2e2e792f0ba

diff --git a/icu4c/source/configure b/icu4c/source/configure
--- a/icu4c/source/configure
+++ b/icu4c/source/configure
@@ -3692,9 +3692,9 @@ echo "$as_me:$LINENO: checking for library API export" >&5
 echo $ECHO_N "checking for library API export... $ECHO_C" >&6
 SHAREDLIBEXPORT=no
 U_USE_GCC_VISIBILITY_ATTRIBUTE=0
+OLD_CFLAGS="${CFLAGS}"
+OLD_CXXFLAGS="${CXXFLAGS}"
 if test "$ac_cv_c_compiler_gnu" = yes; then
-    OLD_CFLAGS="${CFLAGS}"
-    OLD_CXXFLAGS="${CXXFLAGS}"
     LIBCFLAGS="-fvisibility=hidden"
     LIBCXXFLAGS="-fvisibility=hidden"
     CFLAGS="${CFLAGS} ${LIBCFLAGS}"
@@ -3746,18 +3746,81 @@ SHAREDLIBEXPORT=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-    # Restore to their original state because the Intel compiler chokes
-    # on this option when checking for the wchar_t size, but the
-    # option otherwise works.
-    CFLAGS="${OLD_CFLAGS}"
-    CXXFLAGS="${OLD_CXXFLAGS}"
     if test "$SHAREDLIBEXPORT" = no; then
         LIBCFLAGS=
         LIBCXXFLAGS=
     else
         U_USE_GCC_VISIBILITY_ATTRIBUTE=1
     fi
+else
+    case "${host}" in
+    *-*-solaris*)
+        LIBCFLAGS="-xldscope=hidden"
+        LIBCXXFLAGS="-xldscope=hidden"
+        CFLAGS="${CFLAGS} ${LIBCFLAGS}"
+        CXXFLAGS="${CXXFLAGS} ${LIBCXXFLAGS}"
+        cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+__global void f(void);
+#include <stdlib.h>
+int
+main ()
+{
+exit(0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  SHAREDLIBEXPORT=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+SHAREDLIBEXPORT=no
 fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+        if test "$SHAREDLIBEXPORT" = no; then
+            LIBCFLAGS=
+            LIBCXXFLAGS=
+        fi
+        ;;
+    *-*-hpux*)
+                ;;
+    *)
+    esac
+fi
+# Restore to their original state because the Intel compiler chokes
+# on this option when checking for the wchar_t size, but the
+# option otherwise works.
+CFLAGS="${OLD_CFLAGS}"
+CXXFLAGS="${OLD_CXXFLAGS}"
 echo "$as_me:$LINENO: result: $SHAREDLIBEXPORT" >&5
 echo "${ECHO_T}$SHAREDLIBEXPORT" >&6
 
